{
 "title": "Consumer Group Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric", "label": "Select Metric", "query": "lag,poffset,coffset" },
   { "name": "consumergroup", "label": "Select Consumer group", "query": "label_values(consumergroup)" },
   { "name": "timeinterval", "label": "Time Interval", "query": "5m,10m,30m,1h,3h,6h" }
  ]
 },
 "panels": [
  {
   "title": "Producer Offset count by Partition",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poffset{consumergroup =~ \"$consumergroup\"})"
    }
   ]
  },
  {
   "title": "By Consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poffset{consumergroup =~ \"$consumergroup\"}"
    },
    {
     "expr": "coffset{consumergroup =~ \"$consumergroup\"}"
    },
    {
     "expr": "lag{consumergroup =~ \"$consumergroup\"}"
    }
   ]
  },
  {
   "title": "Rate of data by Consumer Group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(poffset{consumergroup =~ \"$consumergroup\"}[$timeinterval])"
    },
    {
     "expr": "rate(coffset{consumergroup =~ \"$consumergroup\"}[$timeinterval])"
    },
    {
     "expr": "rate(lag{consumergroup =~ \"$consumergroup\"}[$timeinterval])"
    }
   ]
  },
  {
   "title": "Metric Offset count by Partition and Metric",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum($metric{consumergroup =~ \"$consumergroup\"})"
    }
   ]
  },
  {
   "title": "By Consumer group and Metric",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$metric{consumergroup =~ \"$consumergroup\"}"
    }
   ]
  },
  {
   "title": "Rate of Data by Consumer Group and Metric",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate($metric{consumergroup =~ \"$consumergroup\"}[$timeinterval])"
    }
   ]
  }
 ]
}