{
 "title": "Topic Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "topic", "label": "Select Topic Name", "query": "label_values(topic)" },
   { "name": "metric", "label": "Select Metric", "query": "lag,poffset,coffset" },
   { "name": "timeinterval", "label": "Time Interval", "query": "5m,10m,30m,1h,3h,6h" }
  ]
 },
 "panels": [
  {
   "title": "Count By Topic in Producer Offset",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poffset{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "By Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poffset{topic=~\"$topic\"}"
    },
    {
     "expr": "coffset{topic=~\"$topic\"}"
    },
    {
     "expr": "lag{topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Rate of Data vs Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(poffset{topic=~\"$topic\"}[$timeinterval])"
    },
    {
     "expr": "rate(coffset{topic=~\"$topic\"}[$timeinterval])"
    },
    {
     "expr": "rate(lag{topic=~\"$topic\"}[$timeinterval])"
    }
   ]
  },
  {
   "title": "Count By Metric and Topic",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum($metric{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "By Metric and Topic ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$metric{topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Rate of Data vs Topic by Metric",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate($metric{topic =~ \"$topic\"}[$timeinterval])"
    }
   ]
  }
 ]
}