{
 "title": "AIO Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metric", "query": "poffset,coffset,lag" },
   {
    "name": "consumergroup",
    "label": "Select Consumer Group",
    "query": "label_values($metric,consumergroup)"
   },
   {
    "name": "topic",
    "label": "Select Topic Name",
    "query": "label_values($metric{consumergroup=~ \"$consumergroup\"},topic)"
   },
   {
    "name": "partition",
    "query": "label_values($metric{consumergroup=~ \"$consumergroup\",topic=~ \"$topic\"},partition)"
   },
   { "name": "timeinterval", "label": "Time Interval", "query": "5m,10m,30m,1h,3h,6h" }
  ]
 },
 "panels": [
  {
   "title": "Producer offset count  for $topic",
   "type": "singlestat",
   "description": "Shows the $metric for given Topic",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poffset{topic=~\"$topic\" , consumergroup =~\"$consumergroup\" , partition=~ \"$partition\"})"
    }
   ]
  },
  {
   "title": "Consumer offset count  for $topic",
   "type": "singlestat",
   "description": "Shows the consumer offset for given Topic",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(coffset{topic=~\"$topic\" , consumergroup =~\"$consumergroup\" , partition=~ \"$partition\"})"
    }
   ]
  },
  {
   "title": "Lag count  for $topic",
   "type": "singlestat",
   "description": "Shows the lag for given Topic",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lag{topic=~\"$topic\" , consumergroup =~\"$consumergroup\" , partition=~ \"$partition\"})"
    }
   ]
  },
  {
   "title": "Max producer offset rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(poffset{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}[$timeinterval]))"
    }
   ]
  },
  {
   "title": "Max consumer offset rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(coffset{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}[$timeinterval]))"
    }
   ]
  },
  {
   "title": "Max lag rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(rate(lag{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}[$timeinterval]))"
    }
   ]
  },
  {
   "title": "Producer Offset ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "poffset{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}",
     "legendFormat": " {{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Rate of producer offset data",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(poffset{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}[$timeinterval])",
     "legendFormat": "{{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Consumer Offset ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "coffset{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}",
     "legendFormat": " {{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Rate of Consumer offset Data ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coffset{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}[$timeinterval])",
     "legendFormat": "{{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Lag data",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lag{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}",
     "legendFormat": " {{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Rate of lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lag{topic=~\"$topic\", consumergroup=~\"$consumergroup\", partition =~ \"$partition\"}[$timeinterval])",
     "legendFormat": "{{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  }
 ]
}