{
 "title": "Alert Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory used alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(httpmetrics{jvmmetrics=\"jvm.memory.totalUsed\"})"
    }
   ]
  },
  {
   "title": "Heap used alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(httpmetrics{jvmmetrics=\"jvm.memory.heapUsed\"})"
    }
   ]
  },
  {
   "title": "Rate of lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lag{}[5m])",
     "legendFormat": "{{topic}} - {{partition}} -{{consumergroup}}"
    }
   ]
  }
 ]
}