{
 "title": "Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bytes In Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "httpmetrics{BrokerTopicMetrics=\"kafka.server.BrokerTopicMetrics.BytesInPerSec.count\",broker=\"http://localhost:8080/api/metrics\",instance=\"localhost:8765\",job=\"kafka_monitor\"}",
     "legendFormat": "Bytes in per Sec"
    }
   ]
  },
  {
   "title": "Bytes out Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "httpmetrics{BrokerTopicMetrics=\"kafka.server.BrokerTopicMetrics.BytesOutPerSec.count\",broker=\"http://localhost:8080/api/metrics\",instance=\"localhost:8765\",job=\"kafka_monitor\"}",
     "legendFormat": "Bytes out per Sec"
    }
   ]
  },
  {
   "title": "Bytes Rejected Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "httpmetrics{BrokerTopicMetrics=\"kafka.server.BrokerTopicMetrics.BytesRejectedPerSec.count\",broker=\"http://localhost:8080/api/metrics\",instance=\"localhost:8765\",job=\"kafka_monitor\"}",
     "legendFormat": "BytesRejectedPerSec"
    }
   ]
  },
  {
   "title": "Total Fetch Requests Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "httpmetrics{BrokerTopicMetrics=\"kafka.server.BrokerTopicMetrics.TotalFetchRequestsPerSec.count\",broker=\"http://localhost:8080/api/metrics\",instance=\"localhost:8765\",job=\"kafka_monitor\"}",
     "legendFormat": "TotalFetchRequestsPerSec"
    }
   ]
  },
  {
   "title": "Failed Fetch Requests Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "httpmetrics{BrokerTopicMetrics=\"kafka.server.BrokerTopicMetrics.FailedFetchRequestsPerSec.count\",broker=\"http://localhost:8080/api/metrics\",instance=\"localhost:8765\",job=\"kafka_monitor\"}",
     "legendFormat": "FailedFetchRequestsPerSec"
    }
   ]
  },
  {
   "title": "Total Produce Requests Per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "httpmetrics{BrokerTopicMetrics=\"kafka.server.BrokerTopicMetrics.TotalProduceRequestsPerSec.count\",broker=\"http://localhost:8080/api/metrics\",instance=\"localhost:8765\",job=\"kafka_monitor\"}",
     "legendFormat": "TotalProduceRequestsPerSec"
    }
   ]
  }
 ]
}